### ISSUE TITLE
Newly released v2.24 is not compatible with Node v12

### ISSUE THREAD

**Issue by khitrenovich** [aws-amplify/amplify-codegen#130]
This is what I see my GitHub Actions build on Node v12 when running `amplify codegen` with AWS Ampify CLI - 

```
Initializing new Amplify CLI version...
Done initializing new version.
Scanning for plugins...
Plugin scan successful
Unexpected token '.'
/opt/hostedtoolcache/node/12.21.0/x64/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/models.js:151
  const codegenPluginsInfo = context?.pluginPlatform?.plugins?.codegen;
                                     ^

SyntaxError: Unexpected token '.'
    at Object.compileFunction (vm.js:379:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.<anonymous> (/opt/hostedtoolcache/node/12.21.0/x64/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/index.js:7:24)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at /opt/hostedtoolcache/node/12.21.0/x64/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:167:74
    at async getHandler (/opt/hostedtoolcache/node/12.21.0/x64/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:167:26)
    at async executePluginModuleCommand (/opt/hostedtoolcache/node/12.21.0/x64/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:160:21)
    at async Object.executeCommand (/opt/hostedtoolcache/node/12.21.0/x64/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/opt/hostedtoolcache/node/12.21.0/x64/lib/node_modules/@aws-amplify/cli/lib/index.js:112:9)
```

Possible culprit - #129, specifically [this line](https://github.com/aws-amplify/amplify-codegen/pull/129/files#diff-9cdc392599e83dc816cb33512961b1b923e38faa0692da825ccdaa048081cc6bR151).

**Comment by khitrenovich** [comment]
@phani-srikar ^^ FYI

**Comment by phani-srikar** [comment]
A fix is being released. Thanks for reporting @khitrenovich

**Comment by khitrenovich** [comment]
Looks better now. Thank you for the quick turnaround :)
