### ISSUE TITLE
Setting up local development environment `yarn setup-dev` fails

### ISSUE THREAD

**Issue by jevakallio** [aws-amplify/amplify-codegen#283]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/master/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm (but not relevant here)

### If applicable, what version of Node.js are you using?

Tried: 16.0.0, 16.3.0 LTS, 17.0.1 (latest)

### Amplify CLI Version

6.3.0 (but not relevant here)

### What operating system are you using?

MacOS Catalina 10.15.7 (Intel)

### Amplify Codegen Command

Not applicable

### Describe the bug

I wanted to contribute a fix to https://github.com/aws-amplify/amplify-codegen/issues/241 (adding support for [`@aws_lambda`](https://aws.amazon.com/blogs/mobile/appsync-lambda-auth/) authorization directive, which currently breaks `amplify codegen` for all published versions of Amplify CLI)

However I'm not able to setup the local development environment. Following the instructions from README:

```sh
$ git clone git@github.com:[username]/amplify-codegen.git
$ cd amplify-codegen

$ yarn setup-dev
```

Running `yarn setup-dev` fails with:
```
error /Users/swanson/dev/amplify-codegen/node_modules/node-pty-prebuilt-multiarch: Command failed.
Exit code: 1
Command: prebuild-install || node scripts/install.js
Arguments:
Directory: /Users/swanson/dev/amplify-codegen/node_modules/node-pty-prebuilt-multiarch
Output:
prebuild-install WARN install No prebuilt binaries found (target=17.0.0 runtime=node arch=x64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.1
gyp info using node@17.0.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp http GET https://nodejs.org/download/release/v17.0.0/node-v17.0.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v17.0.0/node-v17.0.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v17.0.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v17.0.0/SHASUMS256.txt
(node:15281) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/swanson/dev/amplify-codegen/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/swanson/dev/amplify-codegen/node_modules/node-pty-prebuilt-multiarch/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/swanson/dev/amplify-codegen/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/swanson/Library/Caches/node-gyp/17.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/swanson/dev/amplify-codegen/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/swanson/Library/Caches/node-gyp/17.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/swanson/dev/amplify-codegen/node_modules/node-pty-prebuilt-multiarch',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/pty/src/unix/pty.o
In file included from ../src/unix/pty.cc:20:
In file included from ../../nan/nan.h:58:
In file included from /Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/node.h:63:
In file included from /Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/v8.h:25:
In file included from /Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/v8-array-buffer.h:12:
In file included from /Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/v8-local-handle.h:12:
/Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/v8-internal.h:566:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:697:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
In file included from ../src/unix/pty.cc:20:
In file included from ../../nan/nan.h:58:
In file included from /Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/node.h:63:
In file included from /Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/v8.h:25:
In file included from /Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/v8-array-buffer.h:13:
In file included from /Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/v8-object.h:10:
/Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/v8-persistent-handle.h:10:10: fatal error: 'v8-weak-callback-info.h' file not found
#include "v8-weak-callback-info.h"  // NOLINT(build/include_directory)
         ^~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/swanson/dev/amplify-codegen/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/swanson/.nvm/versions/node/v17.0.0/bin/node" "/Users/swanson/dev/amplify-codegen/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/swanson/dev/amplify-codegen/node_modules/node-pty-prebuilt-multiarch
```

From the README

> You will need the latest version of nodejs on your system and developing locally also requires yarn workspaces

I have tried with nodejs versions 16.0.0, 16.3.0 (latest LTS) and 17.0.0 (latest published) with same results.

### Expected behavior

`yarn setup-dev` completes without errors

### Reproduction steps

1. Clone fresh copy of the repository (tested commit ff9d1a9b3da413981824bc140e973e3b7dd7e91f)
2. Run `yarn setup-dev`

### Log output

<details>

```
➜  amplify-codegen git:(master) yarn setup-dev
yarn run v1.22.4
$ (yarn && lerna run build) && yarn add-cli-no-save && (yarn hoist-cli && yarn rm-dev-link && yarn link-dev)
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning lerna > @lerna/version > temp-write > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning lerna > @lerna/bootstrap > @lerna/run-lifecycle > npm-lifecycle > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning lerna > @lerna/bootstrap > @lerna/run-lifecycle > npm-lifecycle > node-gyp > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning lerna > @lerna/bootstrap > @lerna/run-lifecycle > npm-lifecycle > node-gyp > request > har-validator@5.1.5: this library is no longer supported
warning lerna > @lerna/create > globby > fast-glob > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning lerna > @lerna/create > globby > fast-glob > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning lerna > @lerna/bootstrap > @lerna/symlink-dependencies > @lerna/create-symlink > @zkochan/cmd-shim > mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
warning @commitlint/cli > babel-polyfill > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning @commitlint/cli > babel-polyfill > babel-runtime > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning codecov@3.8.3: https://about.codecov.io/blog/codecov-uploader-deprecation-plan/
warning jest > @jest/core > jest-haste-map > sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
warning jest > @jest/core > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning jest > @jest/core > jest-config > jest-environment-jsdom > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning jest-junit > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > codecov@3.8.3: https://about.codecov.io/blog/codecov-uploader-deprecation-plan/
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-appsync > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-sdk > uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen > graphql-config > graphql-import@0.7.1: GraphQL Import has been deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-import for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-amplify > @aws-amplify/datastore > uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-amplify > @aws-amplify/analytics > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-sdk > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-appsync > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-sdk > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-amplify > @aws-amplify/predictions > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-amplify > @aws-amplify/pubsub > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-amplify > @aws-amplify/core > @aws-sdk/client-cognito-identity > @aws-sdk/middleware-retry > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen > @graphql-codegen/core > @graphql-toolkit/common@0.6.6: GraphQL Toolkit is deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-toolkit for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > @aws-amplify/appsync-modelgen-plugin > @graphql-codegen/visitor-plugin-common > @graphql-codegen/plugin-helpers > @graphql-toolkit/common@0.9.7: GraphQL Toolkit is deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-toolkit for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen > @graphql-codegen/core > @graphql-codegen/plugin-helpers > @graphql-toolkit/common@0.6.6: GraphQL Toolkit is deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-toolkit for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > @aws-amplify/appsync-modelgen-plugin > @graphql-codegen/visitor-plugin-common > @graphql-toolkit/relay-operation-optimizer > @graphql-toolkit/common@0.9.7: GraphQL Toolkit is deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-toolkit for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen > @graphql-codegen/core > @graphql-toolkit/schema-merging > @graphql-toolkit/common@0.6.6: GraphQL Toolkit is deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-toolkit for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-amplify > @aws-amplify/api > @aws-amplify/api-graphql > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-amplify > @aws-amplify/predictions > @aws-sdk/client-comprehend > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-amplify > @aws-amplify/predictions > @aws-sdk/client-translate > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen > @graphql-codegen/core > @graphql-toolkit/common > @kamilkisiela/graphql-tools > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > @aws-amplify/appsync-modelgen-plugin > @graphql-codegen/visitor-plugin-common > @graphql-codegen/plugin-helpers > @graphql-toolkit/common > @ardatan/graphql-tools > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > @aws-amplify/appsync-modelgen-plugin > @graphql-codegen/visitor-plugin-common > @graphql-toolkit/relay-operation-optimizer > relay-compiler > fbjs > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "lerna > @lerna/version > @lerna/github-client > @octokit/rest > @octokit/plugin-request-log@1.0.4" has unmet peer dependency "@octokit/core@>=3".
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0".
warning " > pretty-quick@3.1.1" has incorrect peer dependency "prettier@>=2.0.0".
warning " > @aws-amplify/appsync-modelgen-plugin@1.29.2" has unmet peer dependency "graphql@^14.5.8".
warning "workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > graphql-tag@2.12.5" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
warning "workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-appsync@4.1.4" has unmet peer dependency "graphql@0.13.0 | 14.x | 15.x".
warning "workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-appsync > apollo-cache-inmemory@1.3.12" has unmet peer dependency "graphql@0.11.7 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-appsync > apollo-link@1.2.5" has unmet peer dependency "graphql@^0.11.3 || ^0.12.3 || ^0.13.0 || ^14.0.0".
warning "workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-appsync > apollo-client@2.4.6" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-appsync > apollo-client > apollo-link@1.2.14" has unmet peer dependency "graphql@^0.11.3 || ^0.12.3 || ^0.13.0 || ^14.0.0 || ^15.0.0".
warning "workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-appsync > apollo-link-http@1.5.8" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-appsync > redux-thunk@2.4.0" has incorrect peer dependency "redux@^4".
warning "workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-appsync > @aws-sdk/lib-storage@3.39.0" has unmet peer dependency "@aws-sdk/abort-controller@^3.0.0".
warning "workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > @aws-amplify/appsync-modelgen-plugin > @graphql-codegen/testing@1.17.7" has unmet peer dependency "jest-diff@^23.0.0 || ^24.0.0 || ^25.0.0 || ^26.0.0".
warning "workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-appsync > @aws-sdk/client-s3 > @aws-sdk/middleware-sdk-s3@3.39.0" has unmet peer dependency "@aws-sdk/signature-v4-crt@^3.31.0".
warning "workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-appsync > apollo-cache-inmemory > apollo-cache@1.3.5" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
warning "workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-appsync > apollo-cache-inmemory > apollo-utilities@1.3.4" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
warning "workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-appsync > apollo-link-http > apollo-link-http-common@0.2.16" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
warning "workspace-aggregator-15974897-8e8a-4a9f-b8f0-d74c613e2cbb > amplify-codegen-e2e-tests > aws-amplify > @aws-amplify/core > @aws-sdk/client-cognito-identity > @aws-sdk/middleware-retry > react-native-get-random-values@1.7.0" has unmet peer dependency "react-native@>=0.56".
[4/4] 🔨  Building fresh packages...
[-/7] ⠈ waiting...
[-/7] ⠈ waiting...
[-/7] ⠈ waiting...
[-/7] ⠈ waiting...
error /Users/swanson/dev/amplify-codegen/node_modules/node-pty-prebuilt-multiarch: Command failed.
Exit code: 1
Command: prebuild-install || node scripts/install.js
Arguments:
Directory: /Users/swanson/dev/amplify-codegen/node_modules/node-pty-prebuilt-multiarch
Output:
prebuild-install WARN install No prebuilt binaries found (target=17.0.0 runtime=node arch=x64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.1
gyp info using node@17.0.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp http GET https://nodejs.org/download/release/v17.0.0/node-v17.0.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v17.0.0/node-v17.0.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v17.0.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v17.0.0/SHASUMS256.txt
(node:15281) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/swanson/dev/amplify-codegen/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/swanson/dev/amplify-codegen/node_modules/node-pty-prebuilt-multiarch/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/swanson/dev/amplify-codegen/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/swanson/Library/Caches/node-gyp/17.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/swanson/dev/amplify-codegen/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/swanson/Library/Caches/node-gyp/17.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/swanson/dev/amplify-codegen/node_modules/node-pty-prebuilt-multiarch',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/pty/src/unix/pty.o
In file included from ../src/unix/pty.cc:20:
In file included from ../../nan/nan.h:58:
In file included from /Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/node.h:63:
In file included from /Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/v8.h:25:
In file included from /Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/v8-array-buffer.h:12:
In file included from /Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/v8-local-handle.h:12:
/Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/v8-internal.h:566:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:697:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
In file included from ../src/unix/pty.cc:20:
In file included from ../../nan/nan.h:58:
In file included from /Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/node.h:63:
In file included from /Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/v8.h:25:
In file included from /Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/v8-array-buffer.h:13:
In file included from /Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/v8-object.h:10:
/Users/swanson/Library/Caches/node-gyp/17.0.0/include/node/v8-persistent-handle.h:10:10: fatal error: 'v8-weak-callback-info.h' file not found
#include "v8-weak-callback-info.h"  // NOLINT(build/include_directory)
         ^~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/swanson/dev/amplify-codegen/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/swanson/.nvm/versions/node/v17.0.0/bin/node" "/Users/swanson/dev/amplify-codegen/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/swanson/dev/amplify-codegen/node_modules/node-pty-prebuilt-multiarch
error Command failed with exit code 1.
```

</details>

**Comment by phani-srikar** [comment]
Hi @jevakallio. Thanks for reporting. Can you please try to use node version below 16 and see if it works? `v15.14.0` works fine.

**Comment by jevakallio** [comment]
@phani-srikar Thank you, I was able to run the development environment for Node 15.

The documentation states:

>  You will need the **latest** version of nodejs on your system and developing locally also requires yarn workspaces.

Might be helpful to update this to specify the known supported version range, as Node 16 is now LTS.
