### ISSUE TITLE
Codegen fails to create dart models after graphql schema compilation

### ISSUE THREAD

**Issue by fireproofpenguin** [aws-amplify/amplify-codegen#342]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/master/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm (with nvm)

### If applicable, what version of Node.js are you using?

16.13.0

### Amplify CLI Version

7.6.5

### What operating system are you using?

Mac Big Sur

### Amplify Codegen Command

codegen models

### Describe the bug

Running `amplify codegen models` after modifying the schema on a freshly created amplify project for flutter / dart, successfully compiles the schema, but then gives the following error:

```
Cannot use GraphQLDirective "@aws_subscribe" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.
```

### Expected behavior

Successful model generation and output into the flutter / dart project

### Reproduction steps

Following the guide provided here:
[Amplify flutter guide](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/flutter/#code-generation-amplify-cli)

Everything goes as planned up to the code generation step.

### GraphQL schema(s)

<details>

```graphql
type Post @model {
  id: ID!
  title: String!
  status: PostStatus!
  rating: Int
  content: String
}

enum PostStatus {
  DRAFT
  PUBLISHED
}


```

</details>

### Log output

<details>
  <summary>Console output</summary>

```
GraphQL schema compiled successfully.

Edit your schema at /Users/<user>/<project>/amplify/backend/api/testApi/schema.graphql or place .graphql files in a directory at /Users/<user>/<project>/amplify/backend/api/testApi/schema

Detected Dart SDK version 2.12.0 or above
Detected feature flag: “enableDartNullSafety : true”
Generating Dart Models with null safety. To opt out of null safe models, turn off the “enableDartNullSafety” feature flag. Learn more: https://docs.amplify.aws/lib/project-setup/null-safety/q/platform/flutter
Cannot use GraphQLDirective "@aws_subscribe" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
Error: Cannot use GraphQLDirective "@aws_subscribe" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (/Users/<user>/.nvm/versions/node/v16.13.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/node_modules/graphql/jsutils/instanceOf.js:28:13)
    at isDirective (/Users/<user>/.nvm/versions/node/v16.13.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/node_modules/graphql/type/directives.js:37:34)
    at Object.isSpecifiedDirective (/Users/<user>/.nvm/versions/node/v16.13.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/node_modules/graphql/type/directives.js:169:10)
    at getDocumentNodeFromSchema (/Users/<user>/.nvm/versions/node/v16.13.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/node_modules/@graphql-tools/utils/index.js:736:21)
    at Object.printSchemaWithDirectives (/Users/<user>/.nvm/versions/node/v16.13.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/node_modules/@graphql-tools/utils/index.js:778:26)
    at Object.exports.plugin (/Users/<user>/.nvm/versions/node/v16.13.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/node_modules/@aws-amplify/appsync-modelgen-plugin/src/plugin.ts:49:23)
    at executePlugin (/Users/<user>/.nvm/versions/node/v16.13.0/lib/node_modules/@aws-amplify/cli/node_modules/@graphql-codegen/core/index.js:38:35)
    at /Users/<user>/.nvm/versions/node/v16.13.0/lib/node_modules/@aws-amplify/cli/node_modules/@graphql-codegen/core/index.js:167:30
    at Array.map (<anonymous>)
    at Object.codegen (/Users/<user>/.nvm/versions/node/v16.13.0/lib/node_modules/@aws-amplify/cli/node_modules/@graphql-codegen/core/index.js:157:54)
    at /Users/<user>/.nvm/versions/node/v16.13.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/models.js:126:23
    at Array.map (<anonymous>)
    at Object.generateModels (/Users/<user>/.nvm/versions/node/v16.13.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/models.js:125:46)
    at Object.run (/Users/<user>/.nvm/versions/node/v16.13.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/commands/codegen/models.js:9:7)
    at Object.executeAmplifyCommand (/Users/<user>/.nvm/versions/node/v16.13.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/amplify-plugin-index.js:9:3)
    at executePluginModuleCommand (/Users/<user>/.nvm/versions/node/v16.13.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
    at executeCommand (/Users/<user>/.nvm/versions/node/v16.13.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
    at Object.run (/Users/<user>/.nvm/versions/node/v16.13.0/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)

```
</details>

<details>
  <summary>Log file</summary>

```
2022-01-05T00:07:45.189Z|info : amplify models codegen
2022-01-05T00:07:45.293Z|info : amplify-cli-core.banner-message/index.ts.fetch banner messages from https://aws-amplify.github.io/amplify-cli/banner-message.json({}
```
</details>

**Comment by alharris-at** [comment]
Hello, are you able to install the latest Amplify CLI with `npm i -g @aws-amplify/cli` and retry this operation? We had a release of this library 6 days ago which contained a bug relating to a graphql dependency update that was subsequently reverted.

**Comment by fireproofpenguin** [comment]
Ah yes, it all seems fixed now. Thanks!
