### ISSUE TITLE
AssertionError when @belongsTo is not on a @model type.

### ISSUE THREAD

**Issue by agenceplus-emillon** [aws-amplify/amplify-codegen#433]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/master/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.0

### Amplify CLI Version

8.2.0

### What operating system are you using?

Windows

### Amplify Codegen Command

codegen models

### Describe the bug

If you make an error in the type of the field referenced by a @belongsTo, it raise an assertion error without indication of the source of error.

### Expected behavior

A nice error.

### Reproduction steps

1. Create a new projet
2. Add provided example schema
3. Execute amplify codegen models

### GraphQL schema(s)

<details>

```graphql
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

type User @model {
  id: ID!
  groupId: Int @index(name: "userByGroup")
  group: String @belongsTo(fields: ["groupId"])
}

type Group @model {
  id: ID!
  users: User @hasMany(indexName: "userByGroup")
}
```

</details>

### Log output

<details>

```
AssertionError [ERR_ASSERTION]: undefined == true
Cannot read property 'fields' of undefined
TypeError: Cannot read property 'fields' of undefined
    at Object.flattenFieldDirectives (C:\snapshot\repo\build\node_modules\@aws-amplify\appsync-modelgen-plugin\lib\utils\process-connections.js:19:11)
    at Object.getBelongsToConnectedField (C:\snapshot\repo\build\node_modules\@aws-amplify\appsync-modelgen-plugin\lib\utils\process-belongs-to.js:37:53)
    at Object.getConnectedFieldV2 (C:\snapshot\repo\build\node_modules\@aws-amplify\appsync-modelgen-plugin\lib\utils\process-connections-v2.js:15:60)
    at Object.processBelongsToConnection (C:\snapshot\repo\build\node_modules\@aws-amplify\appsync-modelgen-plugin\lib\utils\process-belongs-to.js:8:53)
    at Object.processConnectionsV2 (C:\snapshot\repo\build\node_modules\@aws-amplify\appsync-modelgen-plugin\lib\utils\process-connections-v2.js:97:45)
    at C:\snapshot\repo\build\node_modules\@aws-amplify\appsync-modelgen-plugin\lib\visitors\appsync-visitor.js:488:65
    at Array.forEach (<anonymous>)
    at C:\snapshot\repo\build\node_modules\@aws-amplify\appsync-modelgen-plugin\lib\visitors\appsync-visitor.js:487:26
    at Array.forEach (<anonymous>)
    at AppSyncModelJavascriptVisitor.processConnectionDirectivesV2 (C:\snapshot\repo\build\node_modules\@aws-amplify\appsync-modelgen-plugin\lib\visitors\appsync-visitor.js:486:38)
    at AppSyncModelJavascriptVisitor.processDirectives (C:\snapshot\repo\build\node_modules\@aws-amplify\appsync-modelgen-plugin\lib\visitors\appsync-visitor.js:119:18)
    at AppSyncModelJavascriptVisitor.generate (C:\snapshot\repo\build\node_modules\@aws-amplify\appsync-modelgen-plugin\lib\visitors\appsync-javascript-visitor.js:14:14)
    at Object.<anonymous> (C:\snapshot\repo\build\node_modules\@aws-amplify\appsync-modelgen-plugin\lib\plugin.js:51:24)
    at Object.executePlugin (C:\snapshot\repo\build\node_modules\@graphql-codegen\core\dist\commonjs\execute-plugin.js:32:41)
    at C:\snapshot\repo\build\node_modules\@graphql-codegen\core\dist\commonjs\codegen.js:58:47
    at Array.map (<anonymous>)
    at Object.codegen (C:\snapshot\repo\build\node_modules\@graphql-codegen\core\dist\commonjs\codegen.js:48:49)
    at C:\snapshot\repo\build\node_modules\amplify-codegen\src\commands\models.js:133:23
    at Array.map (<anonymous>)
    at Object.generateModels (C:\snapshot\repo\build\node_modules\amplify-codegen\src\commands\models.js:132:46)
    at async Object.run (C:\snapshot\repo\build\node_modules\amplify-codegen\commands\codegen\models.js:9:7)
    at async Object.executeAmplifyCommand (C:\snapshot\repo\build\node_modules\amplify-codegen\src\amplify-plugin-index.js:9:3)
    at async executePluginModuleCommand (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\execution-manager.js:142:5)
    at async executeCommand (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\execution-manager.js:40:9)
    at async Object.run (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\index.js:163:9)
```

</details>

**Comment by alharris-at** [comment]
Confirming that at some point this was updated to provide a friendlier error message. Resolving

<img width="504" alt="Screenshot 2023-03-21 at 12 24 37 PM" src="https://user-images.githubusercontent.com/91494052/226719144-33204f27-e556-4068-a4a1-c9497e8e68e0.png">
